- name: Deploy static website to web servers
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure Apache is installed
      ansible.builtin.package:
        name: apache2
        state: present

    - name: Ensure Apache is enabled and running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Ensure web root exists
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    # Copy common static files
    - name: Copy HTML/CSS/JS files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
      with_fileglob:
        - "*.html"
        - "*.css"
